---
- name: 'update and upgrade packages.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 10080

- name: 'remove dependencies not required'
  become: yes
  apt:
    autoremove: yes

- name: 'install dependencies'
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: 'install pm2'
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: 'extract artifact'
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: 'start application'
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start